export type Role =
  | 'FULL_ACCESS'
  | 'BASIC_ACCESS'
  | 'VIDEO_ACCESS'
  | 'COMMENT_ACCESS';

export enum VALID_ROLES {
  FULL_ACCESS = 'FULL_ACCESS',
  BASIC_ACCESS = 'BASIC_ACCESS',
  VIDEO_ACCESS = 'VIDEO_ACCESS',
  COMMENT_ACCESS = 'COMMENT_ACCESS',
}
